pypics/urls.py
from django.contrib import admin
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from posts.views import PostList, PostCreate, PostDetail

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', PostList.as_view(), name='list'),
    path('new/', PostCreate.as_view(), name='new'),
    path('posts/<pk>/', PostDetail.as_view(), name='detail'),
] + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

posts/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class Post(models.Model):
    name = models.TextField()
    image = models.ImageField()
    description = models.TextField(null=True, blank=True)
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    created = models.DateTimeField(auto_now_add=True)
    modified = models.DateTimeField(auto_now=True)

class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    text = models.TextField()
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    created = models.DateTimeField(auto_now_add=True)
    modified = models.DateTimeField(auto_now=True)

posts/views.py
from django.views.generic.list import ListView
from django.views.generic.edit import CreateView
from django.views.generic.detail import DetailView
from django import forms
from django.shortcuts import redirect
from django.urls import reverse

from posts.models import Post, Comment

class PostList(ListView):
    model = Post    

class PostCreate(CreateView):
    model = Post
    fields = ['name', 'image', 'description', 'author']
    success_url = '/'

class CommentForm(forms.Form):
    comment = forms.CharField()

class  PostDetail(DetailView):
    model = Post

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        context['comment_form'] = CommentForm()
        return context

    def post(self, request, *args, **kwargs): #this function will deal with POST actions 
        comment_form = CommentForm(request.POST)
        if comment_form.is_valid():
            print(request.user)
            print(self.get_object())
            print(comment_form.cleaned_data)
            comment = Comment(
                author=request.user,
                post=self.get_object(),
                text=comment_form.cleaned_data['comment'] 
            )
            print("hello")
            comment.save()
        else: #bad error handling
            raise Exception
        return redirect(reverse('detail', args=[self.get_object().id]))

posts/templates/posts/base.html
<!doctype html>
<html>
	<head>
		<title>pypics</title>
		<link rel="stylesheet" type="text/css" href="/static/css/base-style.css">
		<script src="https://cdnjs.cloudflare.com/ajax/libs/gsap/1.18.3/TweenMax.min.js"></script>	
	</head>
	<body>
		<div class="header">
			<a id="logo" href="/">pypics</a>
			<a id="add_image" href="{% url 'new' %}">POST IMAGE</a>
		</div>
		<div class="container">
			{% block content %}
			{% endblock %}
		</div>	

		<div class="page-container">
			<div class="page"></div>
		</div>
		<script src="http://code.jquery.com/jquery-1.11.0.min.js"></script>
		<script src="/static/js/animation.js"></script>
	</body>
</html>

posts/templates/posts/post_detail.html
<!doctype html>
<html>
	<head>
		<title>PyPics</title>
		<link rel="stylesheet" type="text/css" href="/static/css/post-detail-style.css">
	</head>
	<body>
		<div class="header">
				<a href="/">PyPics</a>
		</div>
		<strong>{{ object.author.username }}</strong><br/>
		<img src="{{object.image.url}}" width=45% height=auto>
		<p><em>{{ object.created }}</em><br/> {{object.description }}</p>
		<ul>
			{%for comment in object.comment_set.all %}
			<li>
				<strong>{{ comment.author }}</strong><br/>
				{{comment.text}}
			</li>
			{% endfor %}
		</ul>
		<form action="{% url 'detail' pk=object.id %}" method="POST">
			{% csrf_token %}
			{{ comment_form.as_p }}
			<input type="submit" value="Comment">
		</form>
	</body>
</html>

posts/templates/posts/post_form.html
<!doctype html>
<html>
	<head>
		<title>PyPics</title>
		<link rel="stylesheet" type="text/css" href="/static/css/post-form-style.css">
	</head>
	<body>
		<div class="header">
			<a href="/">PyPics</a>
		</div>
		<div class="container">
			<h1>Create new post</h1>
			<form action="{%url 'new' %}" method="POST" enctype="multipart/form-data">
				{% csrf_token %}
				{% for field in form %}
				<div class="fieldWrapper">
				    {{ field.errors }}
				    {{ field.label_tag }} {{ field }}
				</div>
			    {% endfor %}
				<input type="submit" value="Post">
			</form>
		</div>
	</body>
</html>

posts/templates/posts/post_list.html
{% extends 'posts/base.html' %}
{% block content %}	
	{%for post in object_list %}
		<div class="post">
			<div class="post-container">
				<a href="{% url 'detail' pk=post.pk %}"></a>
			</div>
			<img src="{{ post.image.url }}" width=400 height=400>
			<div class="details">
				<h2>{{post.name}}</h2>
				<p>{{ post.author.username }} </p><br/>
				<p><em>{{ post.created }}</em><br/>{{post.description}}</p>
			</div>
		</div>
	{% endfor %}
{% endblock %}